import { Currency } from '../../../amount';
import { CalendarDate } from '../../../calendar-date';
import { Account, DailyBalanceResults, Effect, Event } from '../../../timeline';
import { TrackItem } from '../../track-item';
import { ChartSampleSize, Track } from '../reducer/forecast/props';
import * as types from '../types';
export declare function addAccount(account: Account): types.forecast.AddAccount;
export declare function addEffect(accountId: string, effect: Effect): types.forecast.AddEffect;
export declare function addEvent(event: Event): types.forecast.AddEvent;
export declare function addTrack(accountId: string, track: Track): types.forecast.AddTrack;
export declare function exportTimeline(): types.forecast.ExportTimeline;
export declare function importTimeline(data: types.forecast.ImportTimelineData): types.forecast.ImportTimeline;
export declare function setDailyBalanceResults(currency: Currency, results: DailyBalanceResults): types.forecast.SetTrackItemAccruedAmounts;
export declare function removeAccount(accountId: string): types.forecast.RemoveAccount;
export declare function removeEffect(effectId: string): types.forecast.RemoveEffect;
export declare function removeEffectFromAccount(effectId: string, accountId: string): types.forecast.RemoveEffectFromAccount;
export declare function removeEvent(id: string): types.forecast.RemoveEvent;
export declare function selectAccount(accountId: string | null): types.forecast.SelectAccount;
export declare function selectTrackItem(trackItem: TrackItem | null): types.forecast.SelectTrackItem;
export declare function setAccountName(accountId: string, name: string): types.forecast.SetAccountName;
export declare function setEffect(effect: Effect): types.forecast.SetEffect;
export declare function setEvent(event: Event): types.forecast.SetEvent;
export declare function setEventAccountIds(eventId: string, fromAccountId: string | null, toAccountId: string | null): types.forecast.SetEventAccountIds;
export declare function setTimelineCalendarDates(startsOn: CalendarDate, endsOn: CalendarDate): types.forecast.SetTimelineCalendarDates;
export declare function setTimelineChartSampleSize(chartSampleSize: ChartSampleSize): types.forecast.SetTimelineChartSampleSize;
export declare function setTrackItemCalendarDates(accountId: string, trackItem: TrackItem, trackIndex: number, startsOn: CalendarDate | null, endsOn: CalendarDate | null): types.forecast.SetTrackItemCalendarDates;
export declare function setTrackItemEndsOn(accountId: string, trackItem: TrackItem, endsOn: CalendarDate | null): types.forecast.SetTrackItemEndsOn;
export declare function setTrackItemStartsOn(accountId: string, trackItem: TrackItem, startsOn: CalendarDate | null): types.forecast.SetTrackItemStartsOn;
export declare function setTrack(track: Track): types.forecast.SetTrack;
